language: crystal

services:
  - postgresql
  - mysql

env:
  - DATABASE_URL=postgres://postgres@/rome_test
  - DATABASE_URL=mysql://root@localhost/rome_test

before_script:
  - psql -c 'CREATE DATABASE rome_test;' -U postgres
  - mysql -e "CREATE DATABASE rome_test;"

script:
  - crystal run --no-debug `find test -iname "*_test.cr"`
